services:
  v2fly:
    image: v2fly/v2fly-core:latest
    container_name: v2fly
    command: run -c /etc/v2fly/config.json
    volumes:
      - ./v2fly/config.json:/etc/v2fly/config.json
    ports:
      - 10086:10086
      - 10087:10087
    restart: unless-stopped