services:
  flashpaper:
    image: ghcr.io/andrewpaglusch/flashpaper:latest
    container_name: flashpaper
    restart: unless-stopped
    ports:
      - 9041:80
    environment:
      - SITE_TITLE=RAW-Network | Flash Note
      - DISPLAY_LOGO=false
      - DISPLAY_TITLE=false
      - RETURN_FULL_URL=true
      - MAX_SECRET_LENGTH=10000
      - MESSAGES_ERROR_SECRET_TOO_LONG=Message exceeds allowed length.
      - MESSAGES_SUBMIT_SECRET_HEADER=Create an Encrypted Flash Note
      - MESSAGES_SUBMIT_SECRET_SUBHEADER=This message will be destroyed after its read once.
      - MESSAGES_SUBMIT_SECRET_BUTTON=Encrypt & Generate Link
      - MESSAGES_VIEW_CODE_HEADER=One-Time Access Link
      - MESSAGES_VIEW_CODE_SUBHEADER=Share this link securely. It will self-destruct after a single view.
      - MESSAGES_CONFIRM_VIEW_SECRET_HEADER=Decrypt and view this Flash Note?
      - MESSAGES_CONFIRM_VIEW_SECRET_BUTTON=Reveal Message
      - MESSAGES_VIEW_SECRET_HEADER=Flash Note Revealed
      - MESSAGES_VIEW_SECRET_SUBHEADER=This message is no longer available.
      - PRUNE_ENABLED=true
      - PRUNE_MIN_DAYS=30
      - PRUNE_MAX_DAYS=90