services:
  pingvin-share:
    image: stonith404/pingvin-share:latest
    container_name: pingvin-share
    ports:
      - 8099:3000
    volumes:
      - ./data:/opt/app/backend/data
      - ./images:/opt/app/frontend/public/img
    environment:
      - TZ=Asia/Makassar
    restart: unless-stopped
