services:
  gethomepage:
    container_name: homepage
    image: gethomepage/homepage:latest
    ports:
      - 3002:3000
    environment:
      - HOMEPAGE_ALLOWED_HOSTS=*
    volumes:
      - ./config:/app/config
      - ./images:/app/public/images
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
