services:
  sambashare:
    image: dockurr/samba
    container_name: sambashare
    environment:
      - NAME=sambashare
      - USER=username
      - PASS=password
      - UID=1000
      - GID=1000
    ports:
      - 445:445
    volumes:
      - ./storage:/storage
    restart: unless-stopped
