services:
  clypse:
    image: ghcr.io/raw-network/clypse:latest
    container_name: clypse
    ports:
      - 3099:3000
    volumes:
      - ./data:/data
      - ./videos:/videos
    environment:
      - TZ=Asia/Makassar
      - MAX_UPLOAD_SIZE=2G
    restart: unless-stopped
