services:
  clypse:
    image: ghcr.io/raw-network/clypse:latest
    container_name: clypse
    ports:
      - 3099:3000
    volumes:
      - ./data:/data
      - ./videos:/videos
      - ./uploads:/uploads
    environment:
      - TZ=Asia/Makassar
      - MAX_UPLOAD_SIZE=1G
      - MAX_UPLOAD_COUNT=3
    restart: unless-stopped