services:
  convertx:
    image: ghcr.io/c4illin/convertx
    container_name: convertx
    restart: unless-stopped
    ports:
      - 3303:3000
    environment:
      - JWT_SECRET=ThisisVerySecretDontOpenThisfileBecauseIMWachingYou
      - ACCOUNT_REGISTRATION=false
      - HTTP_ALLOWED=true
      - ALLOW_UNAUTHENTICATED=true
      - AUTO_DELETE_EVERY_N_HOURS=24
      - HIDE_HISTORY=true
    volumes:
      - ./data:/app/data